### ISSUE TITLE
Mutated http headers for outgoing requests

### ISSUE THREAD

**Issue by aloukissas** [derekkraan/opentelemetry_honeycomb_sampler#2]
This was a head-scratcher bug that we narrowed it down to introducing this lib. One of our 3rd party APIs started failing, with this error `ERR_HRS_UNAMBIGUOUS_MODE_HTTP_HDR_PARSING` from Akamai. Unfortunately do not have more details on what the headers look like on the receiving end.

One more piece of context: requests were sent with Tesla (1.7.0) with hackney adaptor and we use opentelemetry middleware for Tesla.

**Comment by derekkraan** [comment]
I looked into the Tesla middleware, and it appears that it propagates trace state. Two things:

1. This is probably not what you want. Although the library doesn't seem to offer you an option to disable this. 

2. The trace state, which we are using to carry SampleRate to child spans, is likely being inserted into a header. I am not sure how and I won't have time to look into it until later, but it doesn't seem to me that this should result in an invalid HTTP request. 

Hope this helps. Might be worth raising it as an issue with the Tesla middleware lib.

**Comment by aloukissas** [comment]
Thanks Derek! Will look into this.

**Comment by derekkraan** [comment]
Just looked again. If you are using the middleware from the contrib repo, then you can pass `propagator: :none` to the middleware and the header won't be added. Still worth following up on tracestate causing malformed http headers though, because for internal http requests, you do want to propagate tracestate.
